GET http://localhost:8130/elections/getElectionsList

###
POST http://localhost:8130/elections/addElection
Content-Type: application/json

{
    "electionTitle" : "hij",
    "numDistricts" : 20,
    "constituency" : "hulla",
    "state" : "nt",
    "partiesContesting" : {
        "partyId" : "123",
        "numSeats" : 12
    }
}

###
GET http://localhost:8130/elections/partiesList?electionId=603a17fb2ff58e29ee013456

###
POST http://localhost:8130/elections/addVoter
Content-Type: application/json

{
    "voterID" : "1234",
    "name" : "Shub",
    "DOB" : "30-10-1999",
    "photoURL" : "imgres",
    "gender" : 1,
    "address" : "hmm",
    "constituency" : "hulla",
    "district" : "ok",
    "state" : "hmm",
    "phone" : "9911597216"
}

###
GET http://localhost:8130/elections/verifyUserCreds?voterID=1234&dob=30-10-1999&electionId=603a17fb2ff58e29ee013456